version: "3"
services:
  myInfluxDB:
    image: hypriot/rpi-influxdb
    container_name: myInfluxDB
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports: 
      - "8086:8086"

