version: "3"
services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8088:8088"
            - "8090:8090"
        env_file:
            - 'env.influxdb'
        networks:
            - smarthome
        volumes:
            - dbdata:/var/lib/influxdb
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        env_file:
            - 'env.grafana'
        networks:
            - smarthome
        depends_on:
            - influxdb
        volumes:
            - grafanadata:/var/lib/grafana

networks:
    smarthome:
        
volumes:
    dbdata:
    grafanadata: